Fully understand the failure of building icu tools.
Conclusion first: This is a bazel bug.

How to reproduce the problem:

    Run the following command:
        bazel build third_party/icu:pkgdata

    The following error should pop up:
        error: undefined reference to 'icudt58_dat'

Find the root cause:

    Run the same command with `-s`:
        bazel build third_party/icu:pkgdata -s

    The linker (gcc) was invoked with a parameter file
        bazel-out/local-fastbuild/bin/third_party/icu/pkgdata-2.params,
    which looked like the following chunk of code:
        ```
        --start-lib
        bazel-out/local-fastbuild/bin/third_party/icu/_objs/stubdata/third_party/icu/stubdata/stubdata.pic.o
        --end-lib
        ```

    The linker to link the object files enclosed in the `--start-lib` and
    `--end-lib` pairs.  Removing the `--start-lib` and `--end-lib` pairs and
    re-run the same command the bazel did successfully built the binary.

Resolution:

    Unfortunately, there is no real solution at the moment other than patching
    bazel.

    However, this does not really matter that much as we can still build the icu
    library by
        bazel build third_party/icu:icu,
    in which case bazel decides not to use the `--start-lib` and `--end-lib`
    pairs.

This commit adds a simplified version of the above description to the BUILD file
under third_party/icu.